#!/usr/bin/env python3

import io
import socketserver
import sys

class EchoServerHandler(socketserver.BaseRequestHandler):
  def handle(self):
    data = self.request.recv(4096).decode("utf-8")
    print(data.strip())
    sys.stdout.flush()
    
if __name__ == "__main__":
  with socketserver.TCPServer(("localhost", 9000), EchoServerHandler) as server:
    server.serve_forever()
