#!/usr/bin/env python3

import io
import socketserver
import sys

class EchoServerHandler(socketserver.BaseRequestHandler):
  def handle(self):
    data = self.request.recv(8192).decode("utf-8")
    sys.stdout.write(data)
    sys.stdout.flush()
    
if __name__ == "__main__":
  if "--exit" in sys.argv[1 : ]:
    sys.exit(1)
  with socketserver.TCPServer(("localhost", 9000), EchoServerHandler) as server:
    server.serve_forever()
